### ISSUE TITLE
How do I view the heatmap?

### ISSUE THREAD

**Issue by gowerr** [GrandTheftWalrus/RuneLite-World-Heatmap#4]
Hello, 

I've used the plugin for a while but I have no idea on how to view the HEATMAP. The files are saved as .heatmap - How do I open these?

**Comment by DekuOnyx** [comment]
I don't think this actually works.

**Comment by Fincap** [comment]
When you press `Open Heatmaps Folder` button, there are `Heatmap Files` and `Heatmap Images` folders. The files stored in the `Heatmap Images` folder are actually PNG files, they just aren't saved with a file extension for some reason. If you rename those files to have `.png` at the end, you should be able to view them.

**Comment by DekuOnyx** [comment]
My issue is that there are no .png files, just heatmap files.

**Comment by GrandTheftWalrus** [comment]
Hello all. I'm almost done being busy with university stuff and can finally get around to fixing the heatmap plugin issues. Well, actually it probably won't be until May 15th that I can start, but yee.

When I originally published the plugin, I forgot to add ".png" to the filename of the heatmap images, so on Windows they appear as some sort of unknown file but can be fixed by just adding ".png" to their name (I was developing it on linux where the images would still be recognized as images despite not having the extension)

Although: I'm still not sure what the extent of it is, but for many people the image creation part of the plugin doesn't work at all, in which case there will be a .heatmap file (which is basically a deflated 2D integer matrix), but nothing in the Heatmap Images folder. I'll be fixing this too in about 3 weeks

**Comment by DekuOnyx** [comment]
Thanks for the update! I look forward to using this plugin :)

**Comment by GrandTheftWalrus** [comment]
Hello @gowerr @DekuOnyx @Fincap, I have a shadow JAR aka a preview of the World Heatmap update/fix which you can test out [downloading it here](https://github.com/GrandTheftWalrus/PluginTesting/blob/master/worldheatmap.jar) and then running `java -jar -ea worldheatmap.jar` on it in a terminal. I would recommend making a backup of your ~/.runelite/worldheatmap folder (it's in your home directory) before testing it, just in case something were to go wrong and your original .heatmap files disappeared or something (don't remove it, just make a backup copy of it somewhere)

It would be super coolio if some of you could test it out and tell me if there are still any problems. Also there are some new features. One of em is a heatmap combiner tool that can be used to combine .heatmap files that were saved under different usernames, because originally I forgot to take into account that people's usernames can change. Now, the heatmap files go by unique player ID (and the image filenames properly end with ".png")

![image](https://github.com/GrandTheftWalrus/RuneLite-World-Heatmap/assets/70998757/815929c3-bb2f-42df-95e6-b6d676bcf5e9)

**Comment by Nick2bad4u** [comment]
> Hello @gowerr @DekuOnyx @Fincap, I have a shadow JAR aka a preview of the World Heatmap update/fix which you can test out [downloading it here](https://github.com/GrandTheftWalrus/PluginTesting/blob/master/worldheatmap.jar) and then running `java -jar -ea worldheatmap.jar` on it in a terminal. I would recommend making a backup of your ~/.runelite/worldheatmap folder (it's in your home directory) before testing it, just in case something were to go wrong and your original .heatmap files disappeared or something (don't remove it, just make a backup copy of it somewhere)
> 
> It would be super coolio if some of you could test it out and tell me if there are still any problems. Also there are some new features. One of em is a heatmap combiner tool that can be used to combine .heatmap files that were saved under different usernames, because originally I forgot to take into account that people's usernames can change. Now, the heatmap files go by unique player ID (and the image filenames properly end with ".png")
> 
> ![image](https://user-images.githubusercontent.com/70998757/244392585-815929c3-bb2f-42df-95e6-b6d676bcf5e9.png)

Any idea why this fix hasnt made it to the main client yet?

**Comment by GrandTheftWalrus** [comment]
@Nick2bad4u Ahhh... Well, I was about to add it a few days after leaving that comment, but then it turned out that there was a dependency issue, or something along those lines, and I ended up fixing it and implementing a complicated but successful memory optimization change, and added a yuge amount of updates (the plugin will now track heatmaps of thing such as kills, deaths, loot drops etc.), instead of just having a releasable update.
I'll attach the changelog here so you can see some of what's been done. I'm trying to refrain from making any more additions so that I can just push the zamn update:
[changelog.txt](https://github.com/GrandTheftWalrus/RuneLite-World-Heatmap/files/13259073/changelog.txt)

p.s. the plugin will also allow exporting the full world map including underground areas

**Comment by Nick2bad4u** [comment]
> @Nick2bad4u Ahhh... Well, I was about to add it a few days after leaving that comment, but then it turned out that there was a dependency issue, or something along those lines, and I ended up fixing it and implementing a complicated but successful memory optimization change, and added a yuge amount of updates (the plugin will now track heatmaps of thing such as kills, deaths, loot drops etc.), instead of just having a releasable update. I'll attach the changelog here so you can see some of what's been done. I'm trying to refrain from making any more additions so that I can just push the zamn update: [changelog.txt](https://github.com/GrandTheftWalrus/RuneLite-World-Heatmap/files/13259073/changelog.txt)
> 
> p.s. the plugin will also allow exporting the full world map including underground areas

Omg~~ Im so excited for that update now!

**Comment by Nick2bad4u** [comment]
Did this ever make it into the game?

**Comment by GrandTheftWalrus** [comment]
> Did this ever make it into the game?

After all these millennia the update is pending review by RuneLite and will probs be live in 2 weeks or so 😎 you can see some pics on the new Readme
