### ISSUE TITLE
Files are saved as .heatmap, how do I open this?

### ISSUE THREAD

**Issue by DekuOnyx** [GrandTheftWalrus/RuneLite-World-Heatmap#5]

**Comment by GrandTheftWalrus** [comment]
The .heatmap files in the `Heatmap Files` folder just hold the raw heatmap data (it's a deflated big ass 2D matrix of integers). The plugin is supposed to create an actual PNG file in the `Heatmap Images` folder, but:
- I forgot to append ".png" to the filenames of these images, so Windows doesn't recognize them as images until you add ".png" to the end of their name
- For some people, the image creation doesn't work at all in which case your heatmap data is probably being kept track of, but you won't be able to create the image until I fix it in about 3 weeks

**Comment by oualid6496** [comment]
> The .heatmap files in the `Heatmap Files` folder just hold the raw heatmap data (it's a deflated big ass 2D matrix of integers). The plugin is supposed to create an actual PNG file in the `Heatmap Images` folder, but:
> 
> * I forgot to append ".png" to the filenames of these images, so Windows doesn't recognize them as images until you add ".png" to the end of their name
> * For some people, the image creation doesn't work at all in which case your heatmap data is probably being kept track of, but you won't be able to create the image until I fix it in about 3 weeks

Was the fix ever released? Tried it today but it isn't working

**Comment by GrandTheftWalrus** [comment]
@oualid6496 I started working on it a few days ago, and I was about to be 100% finished until just now when I found out that there is still an issue involving temp files not being deleted by the class BigBufferedImage. All's I have to do is find out how to fix that and then I can release it. Hopefully it doesn't turn out to be super complicated to fix (the class uses some fancy memory mapping stuff that I don't understand yet)

**Comment by GrandTheftWalrus** [comment]
I'm going to share a shadow JAR on this github so that people can test it out, once she's done

**Comment by GrandTheftWalrus** [comment]
Hello @DekuOnyx @oualid6496 , I have a shadow JAR aka a preview of the World Heatmap update/fix which you can test out [downloading it here](https://github.com/GrandTheftWalrus/PluginTesting/blob/master/worldheatmap.jar) and then running `java -jar -ea worldheatmap.jar` on it in a terminal. I would recommend making a backup of your ~/.runelite/worldheatmap folder (it's in your home directory) before testing it, just in case something were to go wrong and your original .heatmap files disappeared or something (don't remove it, just make a backup copy of it somewhere)

It would be super coolio if some of you could test it out and tell me if there are still any problems. Also there are some new features. One of em is a heatmap combiner tool that can be used to combine .heatmap files that were saved under different usernames, because originally I forgot to take into account that people's usernames can change. Now, the heatmap files go by unique player ID (and the image filenames properly end with ".png")

![image](https://github.com/GrandTheftWalrus/RuneLite-World-Heatmap/assets/70998757/815929c3-bb2f-42df-95e6-b6d676bcf5e9)

**Comment by RogueViolation** [comment]
Hi,

I actually tested it out real quick. I launched the .jar file from Powershell, it launcher an instance of RL after which it successfully combined 3 different heatmap files into one and made an image. I didn't check the combined heatmap file, however I did check the image and it seemed to me like the image made sense to be from 3 combined heatmap files. I only created an image using the combiner tool and not the other button since I have a Jagex Account and I reckon I have to be logged in to convert particular heatmap data file to image. All in all it looks good.

**Comment by GrandTheftWalrus** [comment]
> Hi,
> 
> I actually tested it out real quick. I launched the .jar file from Powershell, it launcher an instance of RL after which it successfully combined 3 different heatmap files into one and made an image. I didn't check the combined heatmap file, however I did check the image and it seemed to me like the image made sense to be from 3 combined heatmap files. I only created an image using the combiner tool and not the other button since I have a Jagex Account and I reckon I have to be logged in to convert particular heatmap data file to image. All in all it looks good.

Sweet, thanks a lot for helping to test it out 😎. You can also follow [these steps](https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts) (only took me a minute or two) so that when you do `java -jar -ea worldheatmap.jar` it'll start up logged into your jagex account as per usual

**Comment by Nick2bad4u** [comment]
Any ideas on when the update will hit the RL plugin hub?

**Comment by GrandTheftWalrus** [comment]
> Any ideas on when the update will hit the RL plugin hub?

After all these millennia the update is pending review by RuneLite and will probs be live in 2 weeks or so 😎 you can see some pics on the new Readme
